### ISSUE TITLE
 blog.stigok.com/collections/_posts/2021-04-27-kubernetes-terraform-ingress-nginx-basic-auth-secret.md  state dirty topic

### ISSUE THREAD

**Issue by dominik-ba** [stigok/blog.stigok.com#17]
I just saw your post for the basic auth on the ingress controller (thanks for that snippets!!) and saw your comment about the dirty state:
The [random_password resource has an attribute called keepers](https://registry.terraform.io/providers/hashicorp/random/latest/docs/resources/password)  which can help to only change the random password when something in the related resources changes. That's one possibility to make sure not every plan/apply creates a new password.
Not sure if you knew that.. :)

**Comment by stigok** [comment]
Hey! Thanks for the feedback. Actually, it's not the `random_password` that gets recreated, it's the `bcrypt` function that is being evaluated and returning a new hash value on every plan. I need a kind of `keepers` argument to `bcrypt` instead :)

**Comment by dominik-ba** [comment]
Ah ok gotcha. Then I misunderstood it. Thanks for your answer and thanks again for the sharing the snippets!
